### ISSUE TITLE
Requesting for the callhome result.

### ISSUE THREAD

**Issue by liutaocode** [nttcslab-sp/EEND-vector-clustering#10]
Recently, I want to compare our algorithm with your paper in callhome result. Can you kindly provide the rttm hypothesis of callhome for us in the original paper?  Thanks a lot.

**Comment by nttcslab-sp-admin** [comment]
Thank you for your interest in our work. We have uploaded the RTTM files to the repository.
We hope this will help you.
[egs/callhome/v1/rttm_results/eend-vc_callhome2_hyp_rttm.tar.gz](https://github.com/nttcslab-sp/EEND-vector-clustering/blob/dd1a0cda6b0f61ad5c7eefb47dfc4be67227cb8b/egs/callhome/v1/rttm_results/eend-vc_callhome2_hyp_rttm.tar.gz)
See also the Readme:
[egs/callhome/v1/rttm_results/README](https://github.com/nttcslab-sp/EEND-vector-clustering/blob/dd1a0cda6b0f61ad5c7eefb47dfc4be67227cb8b/egs/callhome/v1/rttm_results/README)

**Comment by liutaocode** [comment]
> Thank you for your interest in our work. We have uploaded the RTTM files to the repository. We hope this will help you. [egs/callhome/v1/rttm_results/eend-vc_callhome2_hyp_rttm.tar.gz](https://github.com/nttcslab-sp/EEND-vector-clustering/blob/dd1a0cda6b0f61ad5c7eefb47dfc4be67227cb8b/egs/callhome/v1/rttm_results/eend-vc_callhome2_hyp_rttm.tar.gz) See also the Readme: [egs/callhome/v1/rttm_results/README](https://github.com/nttcslab-sp/EEND-vector-clustering/blob/dd1a0cda6b0f61ad5c7eefb47dfc4be67227cb8b/egs/callhome/v1/rttm_results/README)

Thanks for the quick reply. This result will help us a lot.
